Repository ECSE-428-Group-5-W-2023/OnCampus, pull requests merged in 2023-03, with the labels that each got.

#106 test(web): remove event test
  web/testing/cypress/e2e/ID009_Remove_Event_From_Schedule.cy.js
Labels: testing

#105 test(web): edit event error flow
  Gherkin Features/ID005_Edit_Unique_Event.feature
  Gherkin Features/ID006_Edit_Recurring_Event.feature
  web/src/components/Schedule/Schedule.jsx
  web/testing/cypress/e2e/ID005_Edit_Unique_Event.cy.js
  web/testing/cypress/e2e/ID006_Edit_Recurring_Event.cy.js
Labels: testing

#107 Delete event test with normal+error flow
  web/testing/cypress/e2e/ID009_Remove_Event_From_Schedule.cy.js
Labels: testing

#112 Test ID002_Display_Schedule
  web/testing/cypress/e2e/ID002_Display_Schedule.cy.js
Labels: testing

#115 feat(web & backend & db): user account feature
  .gitignore
  backend/src/routes/profile.js
  backend/src/server.js
  db/database.sql
  web/src/components/Auth/AccountInfo.jsx
  web/src/components/Navbar/Navbar.jsx
  web/src/helpers/api.js
  web/src/index.jsx
Labels: feature

#118 Create Gherkin: ID014_Connection_Between_Users.feature
  Gherkin Features/ID014_Connection_Between_Users.feature
Labels: groomed, feature

#121 Created ID015_Viewing_Friend_Schedule gherkin file
  Gherkin Features/ID015_Viewing_Friend_Schedule.feature
Labels: groomed, feature

#120 added gherkin for sending friend request feature
  Gherkin Features/ID012_Responding_To_Friend_Requests.feature
Labels: groomed, feature

#129 gherkins ID020_Create_Shared_Events
  Gherkin Features/ID020_Create_Shared_Events.feature
Labels: documentation, groomed

#128 chore(gherkin): create ID013, adding course event using course code
  Gherkin Features/ID013_Adding_course_event_using_code.feature
Labels: documentation, testing

#122 Create ID022_Unfriend_Another_User.feature
  Gherkin Features/ID021_Unfriend_Another_User.feature
Labels: groomed, feature

#136 feat: connection between users (Id014)
  backend/src/routes/friendship.js
  backend/src/server.js
  db/database.sql
  web/src/components/Friendship/Friendship.jsx
  web/src/components/Navbar/Navbar.jsx
  web/src/helpers/api.js
  web/src/index.jsx
Labels: feature

#135 feat(web): allow ICS file import
  backend/src/routes/event.js
  db/database.sql
  web/src/components/Schedule/Schedule.jsx
Labels: enhancement, feature

#137 feat: unfriend another user (ID021)
  backend/src/routes/friendship.js
  web/src/components/Friendship/Friendship.jsx
  web/src/helpers/api.js
Labels: feature

#140 feat(web&backend): group schedule with shared events, leave and join group, search for group, search for friends
  backend/src/routes/event.js
  backend/src/routes/friendGroup.js
  backend/src/routes/friendship.js
  backend/src/routes/users.js
  backend/src/server.js
  db/database.sql
  web/src/components/Common/Button.jsx
  web/src/components/FriendGroup/FriendGroup.jsx
  web/src/components/Friendship/Friendship.jsx
  web/src/components/Navbar/Navbar.jsx
  web/src/components/Schedule/Schedule.jsx
  web/src/helpers/api.js
Labels: enhancement, feature
