Repository ECSE-428-Group-5-W-2023/OnCampus, pull requests merged in 2023-02, with the labels that each got.

#69 feat(web & backend & db): add event creation
  backend/src/routes/event.js
  backend/src/server.js
  db/database.sql
  web/src/components/Schedule/Schedule.jsx
  web/src/helpers/api.js
Labels: feature

#71 chore(docker): fix docker-compose db address in backend
  docker-compose.yml
Labels: bug

#75 View scheudle
  web/package.json
  web/src/components/Schedule/Schedule.jsx
Labels: feature

#77 fix(web): check for undefined
  web/src/components/Schedule/Schedule.jsx
Labels: bug

#74 test(web): setup end to end/integration testing
  web/testing/.gitignore
  web/testing/cypress.config.js
  web/testing/cypress/e2e/navigation.cy.js
  web/testing/cypress/fixtures/example.json
  web/testing/cypress/support/commands.js
  web/testing/cypress/support/e2e.js
  web/testing/package.json
Labels: testing

#79 feat(backend): Finished edit event api method
  backend/src/routes/event.js
  web/src/helpers/api.js
Labels: feature

#78 feat(web): remap to create event
  web/src/components/Schedule/Schedule.jsx
Labels: feature

#80 Delete event API method
  backend/src/routes/event.js
  db/database.sql
  web/src/helpers/api.js
Labels: feature

#86 test(web): create unique event e2e
  web/testing/cypress/e2e/ID001_Create_Unique_Event.cy.js
Labels: testing

#95 test(web): fix different description input
  web/testing/cypress/e2e/ID001_Create_Unique_Event.cy.js
Labels: testing

#97 test(web): cypress add recording option in npm
  web/testing/cypress.config.js
  web/testing/cypress/videos/ID001_Create_Unique_Event.cy.js.mp4
  web/testing/cypress/videos/navigation.cy.js.mp4
  web/testing/package.json
Labels: testing

#98 test(web): edit event
  Gherkin Features/ID005_Edit_Unique_Event.feature
  Gherkin Features/ID006_Edit_Recurring_Event.feature
  web/src/components/Schedule/Schedule.jsx
  web/testing/cypress/e2e/ID005_Edit_Unique_Event.cy.js
  web/testing/cypress/e2e/ID006_Edit_Recurring_Event.cy.js
Labels: testing

#99 feat(web): remove example path, center login button
  web/src/components/Auth/Login.jsx
  web/src/components/Navbar/Navbar.jsx
Labels: enhancement

#100 feat(web): popup for incorrect event dates, added e2e test and correct file naming
  web/package.json
  web/src/components/Common/Popup.jsx
  web/src/components/Schedule/Schedule.jsx
  web/testing/cypress.config.js
  web/testing/cypress/e2e/ID001_Create_Unique_Event.cy.js
  web/testing/cypress/e2e/ID003_Create_Unique_Event.cy.js
Labels: enhancement, feature, testing
